spring:
    application:
        name: GATEWAY-SERVICE
    cloud:
        gateway:
            routes:
                - id: employee-service
                  uri: lb://EMPLOYEE-SERVICE
                  predicates:
                    - Path=/employees/**
                - id: department-service
                  uri: lb://DEPARTMENT-SERVICE
                  predicates:
                    - Path=/departments/**

server:
    port: 8080

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost 


security:
    oauth2:
        resourceserver:
            jwt:
                issuer-uri: http://localhost:9090/realms/springboot-microservice-realm
                jwk-set-uri: 